Detect the LUKS device in kickstart tests
Automatically detect the LUKS device created by Anaconda for the / mount point.
Using /dev/vda2 is no longer valid, because we create an biosboot partition
since Fedora 37, that changes the number of expected partitions.

diff --git a/autopart-encrypted-1.ks.in b/autopart-encrypted-1.ks.in
--- a/autopart-encrypted-1.ks.in
+++ b/autopart-encrypted-1.ks.in
@@ -18,17 +18,26 @@ shutdown
 %end
 
 %post
-# Check if the type of /dev/vda2 is crypto_LUKS.
-crypted="/dev/vda2"
-type="$(blkid -o value -s TYPE ${crypted})"
+# Log the created partitioning.
+lsblk
 
-if [[ "$type" != "crypto_LUKS" ]] ; then
-    echo "*** unexpected type ${type} of ${crypted}" > /root/RESULT
+# Find the LUKS device.
+crypted="$(blkid --match-token TYPE="crypto_LUKS" --output device)"
+
+if [[ $? != 0 ]] ; then
+    echo "*** couldn't find a LUKS device" > /root/RESULT
+    exit 1
+fi
+
+# The LUKS device should be a parent of a root device.
+lsblk ${crypted} --output mountpoints | grep -x /
+
+if [[ $? != 0 ]] ; then
+    echo "*** ${crypted} doesn't contain a root device" > /root/RESULT
     exit 1
 fi
 
 # Try to use the passphrase.
-crypted="/dev/vda2"
 echo "passphrase" | cryptsetup luksOpen --test-passphrase "${crypted}"
 
 if [[ $? != 0 ]] ; then
diff --git a/autopart-luks-2.ks.in b/autopart-luks-2.ks.in
--- a/autopart-luks-2.ks.in
+++ b/autopart-luks-2.ks.in
@@ -21,18 +21,15 @@ shutdown
 
 %post
 
-# Set the crypted device.
-crypted="/dev/vda2"
+# Find the LUKS device.
+crypted="$(blkid --match-token TYPE="crypto_LUKS" --output device)"
 
-# Check if the type of /dev/vda2 is crypto_LUKS.
-type="$(blkid -o value -s TYPE ${crypted})"
-
-if [[ "$type" != "crypto_LUKS" ]] ; then
-    echo "*** unexpected type ${type} of ${crypted}" > /root/RESULT
+if [[ $? != 0 ]] ; then
+    echo "*** couldn't find a LUKS device" > /root/RESULT
     exit 1
 fi
 
-# Check if the LUKS version of /dev/vda2 is luks2.
+# Check if the LUKS version is luks2.
 result="$(cryptsetup luksDump ${crypted} | awk '{ if ($1 == "Version:") print $2; }' )"
 
 if [[ "$result" != "2" ]] ; then
diff --git a/autopart-luks-3.ks.in b/autopart-luks-3.ks.in
--- a/autopart-luks-3.ks.in
+++ b/autopart-luks-3.ks.in
@@ -21,10 +21,15 @@ shutdown
 
 %post
 
-# Set the crypted device.
-crypted="/dev/vda2"
+# Find the LUKS device.
+crypted="$(blkid --match-token TYPE="crypto_LUKS" --output device)"
 
-# Check the PBKDF of /dev/vda2.
+if [[ $? != 0 ]] ; then
+    echo "*** couldn't find a LUKS device" > /root/RESULT
+    exit 1
+fi
+
+# Check the PBKDF of the LUKS device.
 result="$(cryptsetup luksDump ${crypted} | awk '{ if ($1 == "PBKDF:") print $2; }' )"
 
 if [[ "$result" != "pbkdf2" ]] ; then
