Check also the installed environment in groups-and-envs2 (gh1536)

diff --git a/groups-and-envs-2.ks.in b/groups-and-envs-2.ks.in
--- a/groups-and-envs-2.ks.in
+++ b/groups-and-envs-2.ks.in
@@ -33,14 +33,21 @@ platform="$(get_platform @KSTEST_OS_NAME@ @KSTEST_OS_VERSION@)"
 
 # Testing #1 - a package which is part of a group removed from environment should not be installed.
 if [ "${platform:0:4}" == "rhel" ] || [ "${platform:0:6}" == "centos" ] || [ "${platform}" == "fedora-eln" ]; then
-    SENTINEL_PACKAGE=libguestfs
+    DEFAULT_PACKAGE=qemu-kvm
+    REMOVED_PACKAGE=libguestfs
 else
-    SENTINEL_PACKAGE=dnsmasq
+    DEFAULT_PACKAGE=fedora-release-server
+    REMOVED_PACKAGE=dnsmasq
 fi
 
-rpm -q ${SENTINEL_PACKAGE}
+rpm -q ${DEFAULT_PACKAGE}
+if [[ $? != 0 ]]; then
+    echo "*** package ${DEFAULT_PACKAGE} required for the environment was not installed" >> /root/RESULT
+fi
+
+rpm -q ${REMOVED_PACKAGE}
 if [[ $? == 0 ]]; then
-    echo "*** package ${SENTINEL_PACKAGE} from a group removed from the environment was installed" >> /root/RESULT
+    echo "*** package ${REMOVED_PACKAGE} from a group removed from the environment was installed" >> /root/RESULT
 fi
 
 # Testing #2 - bind-chroot is part of the tested group, and should not be installed.
