Use autoconnections detection in network-noipv4-pre
Follow-up of commit b3fe6b7f6d032fc2cf318847b03739ace33023f3

diff --git a/network-noipv4-pre.ks.in b/network-noipv4-pre.ks.in
--- a/network-noipv4-pre.ks.in
+++ b/network-noipv4-pre.ks.in
@@ -26,6 +26,8 @@ shutdown
 
 @KSINCLUDE@ post-nochroot-lib-network.sh
 
+pass_autoconnections_info_to_chroot
+
 check_gui_configurations @KSTEST_NETDEV1@ @KSTEST_NETDEV2@ @KSTEST_NETDEV3@
 
 %end
@@ -38,11 +40,13 @@ check_ifcfg_key_exists @KSTEST_NETDEV2@ BOOTPROTO no
 check_ifcfg_key_exists @KSTEST_NETDEV3@ BOOTPROTO no
 # TODO create test with virtual network having ipv6 enabled (ipv6 only connection)
 #      libvirt default net does not have ipv6 enabled
-if [[ "@KSTEST_OS_NAME@" == "rhel" ]]; then
+detect_nm_has_autoconnections_off
+nm_has_autoconnections_off=$?
+if [[ $nm_has_autoconnections_off -eq 0 ]]; then
     check_device_connected @KSTEST_NETDEV3@ no
     check_device_has_ipv4_address @KSTEST_NETDEV3@ no
 else
-    # Fedora: connection from %pre fails to activate (RA timeout, no ip config)
+    # connection from %pre fails to activate (RA timeout, no ip config)
     # and default con. created by NM (Wired connection 1) is autoactivated again
     check_device_connected @KSTEST_NETDEV3@ yes
     check_device_has_ipv4_address @KSTEST_NETDEV3@ yes
