Add name resolution test to a bootc test (gh1352)

diff --git a/rpm-ostree-container-bootc.ks.in b/rpm-ostree-container-bootc.ks.in
--- a/rpm-ostree-container-bootc.ks.in
+++ b/rpm-ostree-container-bootc.ks.in
@@ -20,6 +20,12 @@ reboot
 
 %post
 
+HOSTNAME=fedoraproject.org
+getent hosts ${HOSTNAME}
+if [[ $? -ne 0 ]]; then
+    echo "*** Failed check: name resolution on ${HOSTNAME} in %post script" >> /root/RESULT
+fi
+
 # Checks after boot
 cat >> /var/lib/extensions/kickstart-tests/usr/libexec/kickstart-test.sh << 'EOF'
 
