Solve problem with missing loop device for 8 build
- The loop device is not in the container automatically it has to be created
first. Let's pre-create the loop 0 and 1 devices always before podman run.

- Drop --device for loop and loop-control, they are not required because
--privileged will mount whole /dev into the container.

diff --git a/.github/workflows/daily-boot-iso-rhel8.yml b/.github/workflows/daily-boot-iso-rhel8.yml
--- a/.github/workflows/daily-boot-iso-rhel8.yml
+++ b/.github/workflows/daily-boot-iso-rhel8.yml
@@ -24,8 +24,15 @@ jobs:
       - name: Build boot.iso with lorax
         run: |
           mkdir build
+
+          # We have to pre-create loop devices because they are not namespaced in kernel so
+          # podman can't access newly created ones. That caused failures of tests when runners
+          # were rebooted.
+          sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
+          sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
+
           # /var/tmp tmpfs speeds up lorax and avoids https://bugzilla.redhat.com/show_bug.cgi?id=1906364
-          sudo podman run --rm -i --privileged --device /dev/loop0 --device /dev/loop-control --tmpfs /var/tmp:rw,mode=1777 --network host -v $PWD/build:/data registry.access.redhat.com/ubi8 <<EOF
+          sudo podman run --rm -i --privileged --tmpfs /var/tmp:rw,mode=1777 --network host -v $PWD/build:/data registry.access.redhat.com/ubi8 <<EOF
           set -eux
 
           # lorax must run on RHEL host to produce RHEL guest images :-(
@@ -102,4 +109,5 @@ jobs:
         run: |
           # just in case it leaves some behind
           sudo losetup -d /dev/loop0 2>/dev/null || true
+          sudo losetup -d /dev/loop1 2>/dev/null || true
           sudo rm -rf build
