Pass the exit code of launcher to the workflow
So that the job succeeds/fails as it used to before using Permian

diff --git a/.github/workflows/scenarios-permian.yml b/.github/workflows/scenarios-permian.yml
--- a/.github/workflows/scenarios-permian.yml
+++ b/.github/workflows/scenarios-permian.yml
@@ -167,3 +167,14 @@ jobs:
           name: 'logs-permian-${{ matrix.scenario }}'
           path: |
             permian/permian.log
+
+      # Keep compatibility of the overall results, Permian now hides the exit code of launcher
+      - name: Pass the launch script exit code
+        working-directory: ./permian
+        run: |
+          rc=$( awk '/Runner return code: /{ print $4 }' permian.log)
+          if [ -n "$rc" ]; then
+            exit $rc
+          else
+            exit 111
+          fi
