Set launcher timeout from workflow job timeout

diff --git a/.github/workflows/scenarios-permian.yml b/.github/workflows/scenarios-permian.yml
--- a/.github/workflows/scenarios-permian.yml
+++ b/.github/workflows/scenarios-permian.yml
@@ -17,6 +17,9 @@ jobs:
     env:
       TEST_JOBS: 16
       GITHUB_TOKEN: /home/github/github-token
+      # Can't figure out how to read the timeout-minutes value defined above
+      # so define it again as environment variable usable in run script
+      TIMEOUT_MINUTES: 480
 
     steps:
       # self-hosted runners don't do this automatically; also useful to keep stuff around for debugging
@@ -69,9 +72,15 @@ jobs:
           fi
           echo "::set-output name=boot_iso::$BOOT_ISO_URL"
 
+      - name: Set launcher timeout from job timeout
+        id: set_timeout
+        run: |
+          set -eux
+          echo "::set-output name=timeout::$(($TIMEOUT_MINUTES-20))m"
+
       - name: Run scenario ${{ matrix.scenario }} in container
         working-directory: ./permian
-        run: sudo --preserve-env=TEST_JOBS PYTHONPATH=${PYTHONPATH:-}:${{ github.workspace }}/tclib ./pipeline --debug-log permian.log -o library.directPath="${{ github.workspace }}/kickstart-tests/testlib" -o kickstart_test.retry_on_failure=True -o workflows.dry_run=False -o kickstart_test.kstest_local_repo="${{ github.workspace }}/kickstart-tests" run_event '{"type":"github.scheduled.daily.kstest.${{ matrix.scenario }}","bootIso":{"x86_64":"${{ steps.boot_iso_from_scenario.outputs.boot_iso }}"}}'
+        run: sudo --preserve-env=TEST_JOBS PYTHONPATH=${PYTHONPATH:-}:${{ github.workspace }}/tclib ./pipeline --debug-log permian.log -o library.directPath="${{ github.workspace }}/kickstart-tests/testlib" -o kickstart_test.retry_on_failure=True -o workflows.dry_run=False -o kickstart_test.kstest_local_repo="${{ github.workspace }}/kickstart-tests" -o kickstart_test.timeout="${{ steps.set_timeout.outputs.timeout }}" run_event '{"type":"github.scheduled.daily.kstest.${{ matrix.scenario }}","bootIso":{"x86_64":"${{ steps.boot_iso_from_scenario.outputs.boot_iso }}"}}'
 
       - name: Collect anaconda logs
         if: always()
